"""Add segmentation_strategy to ClassificationJob

Revision ID: a01886d28c50
Revises: 8664aa3ad06e
Create Date: 2026-08-21 12:31:02.582253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01886d28c50'
down_revision: Union[str, Sequence[str], None] = '8664aa3ad06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_jobs', sa.Column('segmentation_strategy', sa.String(length=50), server_default='sentence', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification_jobs', 'segmentation_strategy')
    # ### end Alembic commands ###
